### ISSUE TITLE
CR 896-Rename terms used in application

### ISSUE THREAD

**Issue by 0340LalitGupta** [Isgec/WebERP1#12]
IT Business Application Change Request Form
Rename as
IT Business Application/Infra Change Request Form

In Joomla Portal
----------------

ERP-LN Change Request
Rename as
IT Change Request

**Comment by 0340LalitGupta** [comment]
Term changed. 
Copied on live.
![image](https://user-images.githubusercontent.com/37236522/120683685-91dc6280-c4bb-11eb-9178-7fa7bff39c9e.png)

![image](https://user-images.githubusercontent.com/37236522/120684077-eed81880-c4bb-11eb-91e9-1a061c381ca8.png)

**Comment by 0340LalitGupta** [comment]
Changes done.
@hariharan-isgec 
This issue can be closed.

**Comment by hariharan-isgec** [comment]
@0340LalitGupta on code review I found changes related to multi company enablememt are also done along with this change. Explain why this anomoly in code
